name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    if: github.base_ref == 'main' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_ENV: ${{ steps.determine_tag.outputs.DEPLOY_ENV }}
      FULL_IMAGE_TAG: ${{ steps.tag_and_push.outputs.FULL_IMAGE_TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Extract version
        run: echo "VERSION=$(cat VERSION | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Extract commit hash and date
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "DATE=$(printenv DATE)"

      - name: Determine Tag Name and Deployment Folder
        id: determine_tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.base_ref }}" == "main" ]]; then
            echo "IMAGE_TAG=${VERSION}-alpha-${DATE}-${COMMIT_HASH}" >> $GITHUB_ENV
            echo "DEPLOY_ENV=develop" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=${VERSION}-${DATE}-${COMMIT_HASH}" >> $GITHUB_ENV
            echo "DEPLOY_ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "Skipping workflow as the branch is not main."
            exit 0
          fi
    
      - name: Build Docker Image
        run: docker build -t stock-analyser .

      - name: Tag and Push Docker Image
        id: tag_and_push
        run: |
          FULL_IMAGE_TAG="${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}"
          echo "*****************FULL_IMAGE_TAG=${FULL_IMAGE_TAG}*************************"
          echo "FULL_IMAGE_TAG=${FULL_IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Tagging Docker image with: $FULL_IMAGE_TAG"

          docker tag stock-analyser "$FULL_IMAGE_TAG"
          docker push "$FULL_IMAGE_TAG"

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag stock-analyser "${{ secrets.ECR_REPOSITORY }}:latest"
            docker push "${{ secrets.ECR_REPOSITORY }}:latest"
          fi

  update-deployment-repo:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          repository: FledglingTraders/stock-analyser-deploy

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update docker-compose.yml
        run: |
          COMPOSE_FILE="${{ needs.build-and-push.outputs.DEPLOY_ENV }}/docker-compose.yml"
          if [[ -f "$COMPOSE_FILE" ]]; then
            echo "*****************FULL_IMAGE_TAG=${{ needs.build-and-push.outputs.FULL_IMAGE_TAG }}*************************"
            sed -i "s|image: .*|image: ${{ needs.build-and-push.outputs.FULL_IMAGE_TAG }}|" "$COMPOSE_FILE"
          else
            echo "ERROR: docker-compose.yml not found at $COMPOSE_FILE!"
            exit 1
          fi
          cat "$COMPOSE_FILE"

      - name: Push Changes
        run: |
          git remote set-url origin git@github.com:FledglingTraders/stock-analyser-deploy.git
          git add .
          git commit -m "Update docker image to ${{ needs.build-and-push.outputs.FULL_IMAGE_TAG }}"
          git push origin main












